In [2]:
import numpy as np

In [3]:
ratings_mat = np.array([[1, 2, 3],
                        [3, 0, 1]])

# Create a 4x2 matrix
similarities = np.array([[0, 1],
                         [2, 3],
                         [0, 1],
                         [2, 3]])

assert ratings_mat.shape == (2, 3)
assert similarities.shape == (4, 2)



a = ratings_mat

s = similarities[0, :]
print(s)
w = ~np.isnan(a)*s.reshape(-1, 1)
w = w/w.sum(axis = 0)
w

[0 1]


array([[0., 0., 0.],
       [1., 1., 1.]])

In [5]:
# Create a 2x3 matrix

ratings_mat = np.array([[1, 2, 3],
                        [3, 0, 1]])
# Create a 4x2 matrix
similarities = np.array([[0, 1],
                         [2, 3],
                         [0, 1],
                         [2, 3]])

assert ratings_mat.shape == (2, 3)
assert similarities.shape == (4, 2)




weights = np.full((similarities.shape[0], ratings_mat.shape[0], ratings_mat.shape[1]), np.NaN)

for i in range(similarities.shape[0]):
    a = ratings_mat
    s = similarities[i, :]
    w = ~np.isnan(a)*s.reshape(-1, 1)
    w = w/w.sum(axis = 0)

    weights[i,:,:] = w      

weights


#================================================================================================================

# for i in range(similarities.shape[0]):
#     for j in range(ratings_mat.shape[1]):
#         a = ratings_mat[:, j]
#         s = similarities[i, :]
#         w = ~np.isnan(a)*s
#         w = w/w.sum(axis = 0)
#         weights[i, :, j] = w 
        


array([[[0. , 0. , 0. ],
        [1. , 1. , 1. ]],

       [[0.4, 0.4, 0.4],
        [0.6, 0.6, 0.6]],

       [[0. , 0. , 0. ],
        [1. , 1. , 1. ]],

       [[0.4, 0.4, 0.4],
        [0.6, 0.6, 0.6]]])

In [3]:
weights

array([[[0. , 0. , 0. ],
        [1. , 1. , 1. ]],

       [[0.4, 0.4, 0.4],
        [0.6, 0.6, 0.6]],

       [[0. , 0. , 0. ],
        [1. , 1. , 1. ]],

       [[0.4, 0.4, 0.4],
        [0.6, 0.6, 0.6]]])

In [99]:
ratings_mat = np.array([[1, 2, 3],
                        [3, 0, 1]])
similarities = np.array([[0, 1],
                         [2, 3],
                         [0, 1],
                         [2, 3]])

assert ratings_mat.shape == (2, 3)
assert similarities.shape == (4, 2)


# Broadcasting to calculate weights
similarities = similarities[:, np.newaxis , :].reshape(4, -1, 1)

a = ratings_mat
w = ~np.isnan(a)*similarities
w = w/w.sum(axis=1, keepdims=True)
w


array([[[0. , 0. , 0. ],
        [1. , 1. , 1. ]],

       [[0.4, 0.4, 0.4],
        [0.6, 0.6, 0.6]],

       [[0. , 0. , 0. ],
        [1. , 1. , 1. ]],

       [[0.4, 0.4, 0.4],
        [0.6, 0.6, 0.6]]])

In [98]:
import numpy as np

# Your 3D array
array_3d = np.array([[[0., 0., 0.],
                      [1., 1., 1.]],
                     
                     [[2., 2., 2.],
                      [3., 3., 3.]],
                     
                     [[0., 0., 0.],
                      [1., 1., 1.]],
                     
                     [[2., 2., 2.],
                      [3., 3., 3.]]])

# Calculate weights
weights = array_3d / np.sum(array_3d, axis=1, keepdims=True)

print(weights)


[[[0.  0.  0. ]
  [1.  1.  1. ]]

 [[0.4 0.4 0.4]
  [0.6 0.6 0.6]]

 [[0.  0.  0. ]
  [1.  1.  1. ]]

 [[0.4 0.4 0.4]
  [0.6 0.6 0.6]]]


Giả sử chúng ta có ma trận `ratings`, trong đó các phần từ thể hiện điểm số mà user đánh giá anime tương ứng

In [83]:
ratings = np.array([[5, 4, np.nan, 1, np.nan], [np.nan, 4, 4, 2, 2],
                    [3, np.nan, np.nan, 5, 5],[np.nan, 3, 4, 4, np.nan]])
ratings

array([[ 5.,  4., nan,  1., nan],
       [nan,  4.,  4.,  2.,  2.],
       [ 3., nan, nan,  5.,  5.],
       [nan,  3.,  4.,  4., nan]])

In [84]:
np.set_printoptions(suppress = True)

Ở đây mình chỉ tính trên 1 user thôi :v còn phần tính trên batch (nhiều user) các bạn sẽ cơ hội tự trải nghiệm. Chúng ta sẽ xây dựng một mô hình đơn giản để dự đoán các phim mà user chưa đánh gía, hay nói cách khác là các ô `NaN`. Đầu tiên, chúng ta tưởng tượng mỗi dòng là một vector ứng với một user. Sau đó, chúng ta tính toán độ tương tự giữa các vector thông qua khoảng cách. 

In [85]:
# Lấy ra user đầu tiên
r0 = ratings[0]

# Lấy tất cả các user trừ cho user đầu tiên để tính khoảng cách, 
# sau đó tính mean của từng dòng để thu được độ tương tự giữa các user đối với user[0]
s = np.nanmean(np.abs(ratings - r0), axis = 1)

s = 1/(s + 0.001)
s

array([1000.        ,    1.99600798,    0.33322226,    0.49975012])

In [86]:
# Lấy ra các cột mà user[0] chưa đánh giá
a = ratings[:, np.isnan(r0)]
a

array([[nan, nan],
       [ 4.,  2.],
       [nan,  5.],
       [ 4., nan]])

In [90]:
# Tạo ma trận trọng số dựa trên độ tương tự
w = ~np.isnan(a)*s.reshape(-1, 1)
# Chuẩn hoá trọng số
w = w/w.sum(axis = 0)
w

array([[0.        , 0.        ],
       [0.79976019, 0.85693889],
       [0.        , 0.14306111],
       [0.20023981, 0.        ]])

In [88]:
# Kết quả dự đoán được
np.nansum(a*w, axis = 0)

array([4.        , 2.42918332])